basePath: /
definitions:
  models.HospitalRequest:
    properties:
      address:
        type: string
      contactPhone:
        type: string
      name:
        type: string
      rooms:
        items:
          type: string
        type: array
    type: object
  models.Response:
    properties:
      message: {}
    type: object
host: localhost:8082
info:
  contact: {}
  title: Hospital Microservice
  version: "1.0"
paths:
  /api/Hospital:
    post:
      consumes:
      - application/json
      description: Add Hospital
      operationId: add-hospital
      parameters:
      - description: Hospital Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.HospitalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: AddHospital
      tags:
      - Hospital
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
