basePath: /
definitions:
  models.HospitalRequest:
    properties:
      address:
        type: string
      contactPhone:
        type: string
      name:
        type: string
      rooms:
        items:
          type: string
        type: array
    type: object
  models.HospitalResponse:
    properties:
      address:
        type: string
      contactPhone:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.Response:
    properties:
      message: {}
    type: object
host: localhost:8082
info:
  contact: {}
  title: Hospital Microservice
  version: "1.0"
paths:
  /api/Hospital:
    get:
      consumes:
      - application/json
      description: List Hospitals
      operationId: list-hospitals
      parameters:
      - description: From
        in: query
        name: from
        required: true
        type: integer
      - description: Count
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.HospitalResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: ListHospitals
      tags:
      - Hospital
    post:
      consumes:
      - application/json
      description: Add Hospital
      operationId: add-hospital
      parameters:
      - description: Hospital Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.HospitalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: AddHospital
      tags:
      - Hospital
  /api/Hospital/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Hospital
      operationId: delete-hospital
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: DeleteHospital
      tags:
      - Hospital
    get:
      consumes:
      - application/json
      description: Get Hospital
      operationId: get-hospital
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HospitalResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: GetHospital
      tags:
      - Hospital
    put:
      consumes:
      - application/json
      description: Update Hospital
      operationId: update-hospital
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Hospital Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.HospitalRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: UpdateHospital
      tags:
      - Hospital
  /api/Hospital/{id}/Rooms:
    get:
      consumes:
      - application/json
      description: Get Hospital Rooms
      operationId: get-hospital-rooms
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: GetHospitalRooms
      tags:
      - Hospital
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
