accountMicroservicePort: "8081"

accountMicroserviceDb:
  host: "localhost"
  port:     "5432"
  username: "postgres"
  dbname:   "account_microservice"
  sslmode:  "disable"

hospitalMicroservicePort: "8082"

hospitalMicroserviceDb:
  host: "localhost"
  port:     "5432"
  username: "postgres"
  dbname:   "hospital_microservice"
  sslmode:  "disable"