basePath: /
definitions:
  models.Response:
    properties:
      message: {}
    type: object
  models.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.SignUpRequest:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  title: Account Microservice
  version: "1.0"
paths:
  /api/Authentication/SignIn:
    post:
      consumes:
      - application/json
      description: Sign Into Account
      operationId: sign-in
      parameters:
      - description: Sign In Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: SignIn
      tags:
      - Authentication
  /api/Authentication/SignOut:
    put:
      consumes:
      - application/json
      description: Sign Out from Account
      operationId: sign-out
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: SignOut
      tags:
      - Authentication
  /api/Authentication/SignUp:
    post:
      consumes:
      - application/json
      description: Create New Account
      operationId: sign-up
      parameters:
      - description: Sign Up Info
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: SignUp
      tags:
      - Authentication
  /api/Authentication/Validate:
    get:
      consumes:
      - application/json
      description: Validate token
      operationId: validate
      parameters:
      - description: Access Token
        in: query
        name: accessToken
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
      summary: Validate
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
